apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo2025
  labels:
    app: flaskdemo2025
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo2025
  template:
    metadata:
      labels:
        app: flaskdemo2025
    spec:
      containers:
      - name: flaskdemo2025
        image: hapra123/flaskdemo:v1
        ports:
        - containerPort: 5000
