apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskapp2025
  name: flaskapp2025
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: flaskapp2025
