apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythonweb
  name: pythonweb
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: pythonweb
